org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3g
# 仅保留 arm64-v8a 产物，配合 R8 全量混淆达成 <10MB 目标
android.defaults.buildfeatures.buildconfig=true
