package com.litemusic.app.feature.auth

import android.net.Uri
import android.webkit.WebView
import android.util.Log
import androidx.webkit.JavaScriptReplyProxy
import androidx.webkit.WebMessageCompat
import androidx.webkit.WebViewCompat
import androidx.webkit.WebViewFeature
import org.json.JSONObject
import java.util.WeakHashMap

/**
 * Opt-in bridge for a QQ page's own one-key click. It forwards only the exact URI generated by
 * QQ after a user gesture; Android then adds the short-lived callback prefix without altering p.
 */
internal object QqNativeHandoffBridge {
    private const val OBJECT_NAME = "nmlAuthHandoff"
    private const val ASSET = "qq_native_handoff_probe.js"
    private val ORIGINS = setOf("https://xui.ptlogin2.qq.com", "https://ui.ptlogin2.qq.com")
    private val registrations = WeakHashMap<WebView, androidx.webkit.ScriptHandler>()

    fun install(webView: WebView, onNativeUri: (String) -> Unit) {
        if (!WebViewFeature.isFeatureSupported(WebViewFeature.WEB_MESSAGE_LISTENER) ||
            !WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT) ||
            registrations.containsKey(webView)
        ) return
        val source = runCatching {
            webView.context.assets.open(ASSET).bufferedReader().use { it.readText() }
        }.getOrNull() ?: return
        val listener = object : WebViewCompat.WebMessageListener {
                override fun onPostMessage(
                    view: WebView,
                    message: WebMessageCompat,
                    sourceOrigin: Uri,
                    isMainFrame: Boolean,
                    replyProxy: JavaScriptReplyProxy,
                ) {
                    val uri = parseTrustedMessage(message.data)
                    val uiTrusted = isTrustedQqLoginUi(view.url)
                    val originTrusted = isTrustedSourceOrigin(sourceOrigin, view.url)
                    val accepted = uri != null && isMainFrame && uiTrusted && originTrusted &&
                        isExactQqNativeHandoffRequest(uri)
                    // Fixed booleans also let the same trusted document inspect delivery when
                    // a device filters application logcat output. No authorization values return.
                    Log.w("NmlAuthProbe", "stage=bridge_message parsed=${uri != null} mainFrame=$isMainFrame uiTrusted=$uiTrusted originTrusted=$originTrusted accepted=$accepted")
                    replyProxy.postMessage("{\"accepted\":$accepted,\"uiTrusted\":$uiTrusted,\"originTrusted\":$originTrusted,\"mainFrame\":$isMainFrame}")
                    if (!accepted || uri == null) return
                    onNativeUri(uri)
                }
            }
        runCatching {
            WebViewCompat.addWebMessageListener(webView, OBJECT_NAME, ORIGINS, listener)
            WebViewCompat.addDocumentStartJavaScript(webView, source, ORIGINS)
        }.onSuccess { handler ->
            registrations[webView] = handler
        }.onFailure {
            // A partial registration must not alter the official webpage's normal fallback.
            runCatching { WebViewCompat.removeWebMessageListener(webView, OBJECT_NAME) }
        }
    }

    fun remove(webView: WebView) {
        val script = registrations.remove(webView) ?: return
        runCatching { WebViewCompat.removeWebMessageListener(webView, OBJECT_NAME) }
        runCatching { script.remove() }
    }

    private fun parseTrustedMessage(data: String?): String? {
        if (data.isNullOrBlank() || data.length > 8_192) return null
        return runCatching {
            val objectValue = JSONObject(data)
            if (objectValue.length() != 2 || objectValue.optString("type") != "qq-native-handoff" ||
                !objectValue.has("uri") || objectValue.opt("uri") !is String
            ) null else objectValue.getString("uri").takeIf { it.length <= 8_192 }
        }.getOrNull()
    }

    private fun isTrustedQqLoginUi(url: String?): Boolean {
        val uri = url?.let(Uri::parse) ?: return false
        return uri.scheme.equals("https", ignoreCase = true) &&
            uri.userInfo == null && uri.port == -1 &&
            uri.host in setOf("xui.ptlogin2.qq.com", "ui.ptlogin2.qq.com") &&
            uri.path == "/cgi-bin/xlogin"
    }

    private fun isTrustedSourceOrigin(origin: Uri, currentUrl: String?): Boolean {
        val current = currentUrl?.let(Uri::parse) ?: return false
        return origin.userInfo == null && origin.port == -1 && origin.path.isNullOrEmpty() &&
            origin.toString().trimEnd('/') in ORIGINS && origin.host.equals(current.host, ignoreCase = true)
    }
}
